// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMc0bhJ54-KPhcLeWSjMYkqSXJN6e4KhQ',
    appId: '1:1760570910:web:e58d76897337272d55c80f',
    messagingSenderId: '1760570910',
    projectId: 'vocayfy-exe',
    authDomain: 'vocayfy-exe.firebaseapp.com',
    storageBucket: 'vocayfy-exe.firebasestorage.app',
    measurementId: 'G-RRRTWYMT0E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2wwofXGlZdZYaCBuEJRaiLzd5kW5noqY',
    appId: '1:1760570910:android:a72acd658c8e14b555c80f',
    messagingSenderId: '1760570910',
    projectId: 'vocayfy-exe',
    storageBucket: 'vocayfy-exe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjvVAd2tT5atptZW3_Msb0EIAHHmOHAeI',
    appId: '1:1760570910:ios:374eec02b16273b655c80f',
    messagingSenderId: '1760570910',
    projectId: 'vocayfy-exe',
    storageBucket: 'vocayfy-exe.firebasestorage.app',
    iosBundleId: 'com.exe201.vocafyMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjvVAd2tT5atptZW3_Msb0EIAHHmOHAeI',
    appId: '1:1760570910:ios:374eec02b16273b655c80f',
    messagingSenderId: '1760570910',
    projectId: 'vocayfy-exe',
    storageBucket: 'vocayfy-exe.firebasestorage.app',
    iosBundleId: 'com.exe201.vocafyMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMc0bhJ54-KPhcLeWSjMYkqSXJN6e4KhQ',
    appId: '1:1760570910:web:ff5797efedcafe8a55c80f',
    messagingSenderId: '1760570910',
    projectId: 'vocayfy-exe',
    authDomain: 'vocayfy-exe.firebaseapp.com',
    storageBucket: 'vocayfy-exe.firebasestorage.app',
    measurementId: 'G-FM9WWX2L85',
  );
}
